# -*- coding: utf-8 -*-
"""Exp 5_34_MLDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zYtZeDISR5fadmyvepIX3ZzzNacrLd4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load Dataset (use the uploaded file path)
df = pd.read_csv("/content/covid19_patient_symptoms_diagnosis.csv")
print("Dataset Shape:", df.shape)
print(df.head())
print("\nColumns:\n", df.columns)

# 2. Identify target column (adjust if name is different)
# Common targets in COVID datasets: 'Outcome', 'Result', 'Severity', 'Diagnosis'
possible_targets = ["Outcome", "Result", "Severity", "Diagnosis", "covid_result", "COVID19"]
target_col = None
for col in possible_targets:
    if col in df.columns:
        target_col = col
        break

if target_col is None:
    # fallback: last column as target (common in many CSVs)
    target_col = df.columns[-1]

print("Target Column Used:", target_col)

X = df.drop(target_col, axis=1)
y = df[target_col]

# 3. Basic cleaning
# Fill missing values
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = X[col].fillna(X[col].mode()[0])
    else:
        X[col] = X[col].fillna(X[col].median())

# 4. Separate categorical & numerical columns
cat_cols = X.select_dtypes(include=['object']).columns
num_cols = X.select_dtypes(exclude=['object']).columns

# 5. Preprocessing pipeline
preprocess = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

# 6. Build full pipeline with SVM
svm = SVC()

pipe = Pipeline(steps=[
    ('preprocess', preprocess),
    ('svm', svm)
])

# 7. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y if y.nunique() > 1 else None
)

# 8. Hyperparameter Tuning
param_grid = {
    'svm__C': [0.1, 1, 10],
    'svm__gamma': ['scale', 0.1, 0.01],
    'svm__kernel': ['rbf']
}

grid = GridSearchCV(pipe, param_grid, cv=5, verbose=1, n_jobs=-1)
grid.fit(X_train, y_train)

print("\nBest Parameters:", grid.best_params_)

# 9. Evaluate Best Model
best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 10. Confusion Matrix Plot
cm = confusion_matrix(y_test, y_pred)
plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix - SVM (COVID Dataset)")
plt.colorbar()
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()